exclude:
  - /^src\/Resources\/contao\/languages/

ignore:
  - 'Mini Model <minimodel@metamodel.me>'

mapping:
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'Ingolf Steinhardt <git@e-spin.de>'
    - 'xantippe <info@e-spin.de>'
    - 'zonky2 <info@e-spin.de>'
    - 'zonky <gitlab@e-spin.de>'
