dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

env:
  - CONTAO_VERSION=~3.5.5

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - >
    if [ "x${TRAVIS_TAG}" != "x" ]; then
      export COMPOSER_ROOT_VERSION=${TRAVIS_TAG}
    else
      export COMPOSER_ROOT_VERSION=$([[ ${TRAVIS_BRANCH} =~ hotfix/([0-9.]*(-(alpha|beta|rc)[0-9]+)?) ]] \
        && echo ${BASH_REMATCH[1]} \
        || echo dev-${TRAVIS_BRANCH})
    fi
  - echo "Using root version ${COMPOSER_ROOT_VERSION}"
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

branches:
  except:
    - /.*-translation/

cache:
  directories:
    - vendor
