services:
    metamodels.contao_frontend_editing.listener.render_item_list:
        class: MetaModels\ContaoFrontendEditingBundle\EventListener\RenderItemListListener
        arguments:
          - '@contao.translation.translator'
          - '@event_dispatcher'
          - '@metamodels.factory'
          - '@cca.dc-general.contao_frontend.editor'
        tags:
          - { name: kernel.event_listener, event: 'metamodels.render-item-list', method: handleFrontendEditingInListRendering }
          - { name: kernel.event_listener, event: 'metamodels.parse-item', method: handleForItemRendering }

    metamodels.contao_frontend_editing.listener.dc-general.action_handler.create_variant:
        class: MetaModels\ContaoFrontendEditingBundle\EventListener\DcGeneral\ActionEvent\CreateVariantHandler
        arguments:
          - '@cca.dc-general.scope-matcher'
          - '@metamodels.factory'
        tags:
          - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    MetaModels\ContaoFrontendEditingBundle\EventListener\DcGeneral\MetaModel\EditButtons\OverrideEditModelButtons:
        public: false
        calls:
            -   method: setScopeDeterminator
                arguments:
                    - '@cca.dc-general.scope-matcher'
        arguments:
            - '@MetaModels\ViewCombination\ViewCombination'
            - '@translator'
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-edit-mode-buttons

    MetaModels\ContaoFrontendEditingBundle\EventListener\DcGeneral\MetaModel\EditButtons\Action\NotSaveEditModelButton:
        public: false
        calls:
            -   method: setScopeDeterminator
                arguments:
                    - '@cca.dc-general.scope-matcher'
        arguments:
            - '@MetaModels\ViewCombination\ViewCombination'
            - '@=service("contao.framework").getAdapter("Contao\\PageModel")'
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                priority: 1024

    MetaModels\ContaoFrontendEditingBundle\EventListener\DcGeneral\MetaModel\EditButtons\Action\ForwardSaveEditModelButton:
        public: false
        calls:
            -   method: setScopeDeterminator
                arguments:
                    - '@cca.dc-general.scope-matcher'
        arguments:
            - '@MetaModels\ViewCombination\ViewCombination'
            - '@=service("contao.framework").getAdapter("Contao\\PageModel")'
            - '@=service("contao.framework").getAdapter("Contao\\StringUtil")'
        tags:
            -   name: kernel.event_listener
                event: dc-general.contao-frontend.handle-submit
                priority: 128

