services:
    metamodels.contao_frontend_editing.render_item_list_listener:
        class: MetaModels\ContaoFrontendEditingBundle\EventListener\RenderItemListListener
        arguments:
          - '@contao.translation.translator'
          - '@event_dispatcher'
          - '@metamodels.factory'
          - '@cca.dc-general.contao_frontend.editor'
        tags:
          - { name: kernel.event_listener, event: 'metamodels.render-item-list', method: handleFrontendEditingInListRendering }
          - { name: kernel.event_listener, event: 'metamodels.parse-item', method: handleForItemRendering }
